### ISSUE TITLE
Delphi 7

### ISSUE THREAD

**Issue by KlausNZ** [MahdiSafsafi/DDetours#38]
Unfortunately the promised compatibility with Delphi 7 is not given.
I guess, there are no plans to assure them, right?

Cheers,
Klaus

**Comment by MahdiSafsafi** [comment]
Hi KlausNZ,
I'm very sorry about being unable to release an update to support Delphi 7.
It's not like I don't want to support old famous Delphi version (especially Delphi 7). It's out of my hands. I have many plans but I don't have much free time. Until DDL v2 support Delphi 7, please consider using v1 (it's compatible with D7) or any alternative library.

Cheers,
Mahdi.

**Comment by mustapha-wang** [comment]
I modified it to compatible with D7.
[DDetours.zip](https://github.com/MahdiSafsafi/DDetours/files/2975993/DDetours.zip)

**Comment by dummzeuch** [comment]
Btw: The current version isn't compatible with Delphi 2007 either: The types Int8 etc. are not known in Delphi 2007.
