### ISSUE TITLE
OpenThread - Wrong Return Value Check

### ISSUE THREAD

**Issue by TorseqTech** [MahdiSafsafi/DDetours#57]
Small issue inside DDetours.pas calls to OpenThread() are being compared to INVALID_HANDLE_VALUE in both ResumeSuspendedThreads() and SuspendAllThreads() when it should be checked against 0 to properly test against failure.

According to MSDN docs for OpenThread
"If the function fails, the return value is NULL."

**Comment by jreo** [comment]
Simple to corret. Just include in uses the unit Variants and corret the code to:

Function SuspendAllThreads
....
....
....
Result := hSnap <> Null;
....
....
...
  if hThread <> Null
....
....
....

function ResumeSuspendedThreads
.....
....
....
.....
.....
    if hThread <> Null
.....
.....
.....
.....
