### ISSUE TITLE
make unit and include file names more specifiv

### ISSUE THREAD

**Issue by dummzeuch** [MahdiSafsafi/DDetours#60]
Could you please make the unit and include file names more specific? In particular the defs.inc file clashes with another include file in a different library (I have asked them to also use a more specific file name.)
Something like ddetoursDefs.inc would be great. A prefix 'dd' or similar for all unit files would also help to prevent file name clashes. For newer Delphi versions a name space like ddetour would also work, but this won't compile with older compilers (e.g. Delphi 7).

**Comment by tondrej** [comment]
It might be useful (for Delphi/Free Pascal opensource projects) to include [jedi.inc](https://github.com/project-jedi/jedi/blob/master/jedi.inc), perhaps by adding [jedi](https://github.com/project-jedi/jedi) as a git submodule.

**Comment by MahdiSafsafi** [comment]
@dummzeuch  thanks for the suggestion ! IMHO, I think the best solution is to have a proper namespace DDetours. but as you said this will not allow the library to compile on older version. For now I just renamed Defs.inc.

@tondrej Thanks man. But for now, DDetours is only using a few compiler definitions. I'll absolutely consider using jedi.inc if the definitions gets more complexes.
